2.1/IAP/django/core/urls.py
from django.urls import path
from . import views 

app_name = 'core'

urlpatterns = [
	path('', views.index, name='index'),
	path('login', views.login, name='login'),
	path('signup', views.signup, name='signup'),
]

2.1/IAP/django/intro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('todo', include('todo.urls')),
]

2.1/IAP/django/todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path("", views.index, name="todo"),
    path("/new-task", views.new_task, name="new_task"),
    path("/tasks-list", views.tasks_list, name="tasks_list"),
]

2.1/IAP/django/core/models.py
from django.db import models

# Create your models here.

2.1/IAP/django/todo/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Task(models.Model):
    title = models.CharField(_("Title"), max_length=50)
    description = models.TextField(_("Description"))
    date_created = models.DateTimeField(_("Date Created"), auto_now=False, auto_now_add=True)

    def __str__(self) -> str:
        return self.title

2.1/IAP/django/core/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "core/index.html")


def login(request):
    return render(request, "core/login.html")


def signup(request):
    return render(request, "core/signup.html")

2.1/IAP/django/todo/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models


# Create your views here.
def index(request):
    return render(request, "todo/index.html")


def new_task(request):
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        task = models.Task.objects.create(title=title, description=description)
        task.save()
        return redirect(reverse("todo:tasks_list"))

    return render(request, "todo/new-task.html")


def tasks_list(request):
    return render(request, "todo/tasks-list.html", {"tasks": models.Task.objects.all()})

2.1/IAP/django/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    {% block body %} {% endblock body %}
  </body>
</html>

2.1/IAP/django/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} Welcome {% endblock title %}
{% block body %}
<h1>Welcome to our website!</h1>
<a href="{% url 'core:login' %}">Log in</a>
<a href="{% url 'core:signup' %}">Sign up</a>
<a href="{% url 'todo:todo' %}"> To do</a>
{% endblock body %}

2.1/IAP/django/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %} Log in {% endblock title %}

{% block body %}
	<form action="POST">
		{% csrf_token %}
		<label for="email">Email</label>
		<input type="email" name="email" placeholder="Enter email" required><br>
		<label for="password1">Password</label>
		<input type="password" placeholder="Enter password" name="password1"><br>
		<button type="submit">Log in</button>
	</form>
{% endblock body %}

2.1/IAP/django/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Sign up {% endblock title %}

{% block body %}
	<form action="POST">
		{% csrf_token %}
		<label for="firstName">First Name</label>
		<input type="text" placeholder="Enter first name" required><br>
		<label for="surname">Surname</label>
		<input type="text" placeholder="Enter surname" required><br>
		<label for="email">Email</label>
		<input type="email" name="email" placeholder="Enter email" required><br>
		<label for="password1">Password</label>
		<input type="password" placeholder="Enter password" name="password1"><br>
		<label for="password2">Confirm Password</label>
		<input type="password" placeholder="Enter password again" name="password2"><br>
		<button type="submit">Sign up</button>
		<button type="reset">Clear</button>
	</form>
{% endblock body %}

2.1/IAP/django/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'todo/css/style.css' %}">
        <title>TODO | {% block title %}{% endblock title %}</title>
    </head>
    <body>
        {% block body %}{% endblock body %}
    </body>
</html>

2.1/IAP/django/templates/todo/index.html
{% extends 'todo/base.html' %}
{% load static %}


{% block title %}Todo{% endblock title %}
{% block body %}
<h1>Tasks</h1>
<span>Welcome, how may we be of service?</span>
<a href="{% url 'todo:new_task' %}">New Task</a>
<a href="{% url 'todo:tasks_list' %}">View Tasks</a>
{% endblock body %}

2.1/IAP/django/templates/todo/new-task.html
{% extends 'todo/base.html' %}


{% block title %}New Task{% endblock title %}
{% block body %}
<form method="post">
  {% csrf_token %}
  <label for="title">Title</label>
  <input type="text" name="title" placeholder="Task title goes here" required />
  <label for="description">Description</label>
  <textarea name="description" placeholder="Enter task description" required></textarea>
  <button type="submit">Add</button>
</form>
{% endblock body %}

2.1/IAP/django/templates/todo/tasks-list.html
{% extends 'todo/base.html' %}
{% block title %}My Tasks{% endblock title %}

{% block body %}
<ul>
	{% for task in tasks %}
		<li>{{task.title}} - {{task.date_created}}</li>
		<li>{{task.description}}</li>
		<br>
	{% empty %}
		<span>No tasks ... yet </span>
	{% endfor %}
</ul>
{% endblock body %}